// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package su.u_c.deadzone.data.State



object StateProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtTdGF0ZS5wcm90byKXAgoFU3RhdGUSJwoHcGxheWVycxgBIAMoCzINLlN0YXRlLlBsYXllclIHcGxheWVycxInCgdidWxsZ
  XRzGAIgAygLMg0uU3RhdGUuQnVsbGV0UgdidWxsZXRzGmYKBlBsYXllchIOCgJpZBgBIAEoBVICaWQSDAoBeBgCIAEoAlIBeBIMC
  gF5GAMgASgCUgF5EhoKCG5pY2tuYW1lGAQgASgJUghuaWNrbmFtZRIUCgVzY29yZRgFIAEoBVIFc2NvcmUaVAoGQnVsbGV0Eg4KA
  mlkGAEgASgFUgJpZBIMCgF4GAIgASgCUgF4EgwKAXkYAyABKAJSAXkSDgoCZHgYBCABKAJSAmR4Eg4KAmR5GAUgASgCUgJkeWIGc
  HJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}