// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package su.u_c.deadzone.data.Shoot



object ShootProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtTaG9vdC5wcm90byJDCgVTaG9vdBIMCgF4GAEgASgCUgF4EgwKAXkYAiABKAJSAXkSDgoCZHgYAyABKAJSAmR4Eg4KAmR5G
  AQgASgCUgJkeWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}