// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package su.u_c.deadzone.data.ID



@SerialVersionUID(0L)
final case class ID(
    id: Int = 0
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[ID] with com.trueaccord.lenses.Updatable[ID] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (id != 0) { __size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = id
        if (__v != 0) {
          _output__.writeInt32(1, __v)
        }
      };
    }
    def mergeFrom(`_input__`: com.google.protobuf.CodedInputStream): su.u_c.deadzone.data.ID.ID = {
      var __id = this.id
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __id = _input__.readInt32()
          case tag => _input__.skipField(tag)
        }
      }
      su.u_c.deadzone.data.ID.ID(
          id = __id
      )
    }
    def withId(__v: Int): ID = copy(id = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = id
          if (__t != 0) __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = su.u_c.deadzone.data.ID.ID
}

object ID extends com.trueaccord.scalapb.GeneratedMessageCompanion[su.u_c.deadzone.data.ID.ID] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[su.u_c.deadzone.data.ID.ID] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): su.u_c.deadzone.data.ID.ID = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    su.u_c.deadzone.data.ID.ID(
      __fieldsMap.getOrElse(__fields.get(0), 0).asInstanceOf[Int]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = IDProto.descriptor.getMessageTypes.get(0)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = su.u_c.deadzone.data.ID.ID(
  )
  implicit class IDLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, su.u_c.deadzone.data.ID.ID]) extends com.trueaccord.lenses.ObjectLens[UpperPB, su.u_c.deadzone.data.ID.ID](_l) {
    def id: com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.id)((c_, f_) => c_.copy(id = f_))
  }
  final val ID_FIELD_NUMBER = 1
}
