// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package su.u_c.deadzone.data.Nick



object NickProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgpOaWNrLnByb3RvIhoKBE5pY2sSEgoEbmFtZRgBIAEoCVIEbmFtZWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}